#! /bin/sh

sxhkd &
#/home/sigma/.scripts/status_panel.sh &
feh --bg-fill --randomize ~/Images/wallpapers/* &
/usr/local/bin/fcitx5 &

bspc monitor -d 1 2 3 4 5

# ---window managment
bspc config border_width			1
bspc config focused_border_color 	"#a7c080"
bspc config window_gap				4
bspc config split_ratio				0.50

bspc config single_monocle			false
bspc config borderless_monocle		true
bspc config gapless_monocle			true

bspc config focus_follows_pointer	true
bspc config pointer_follows_monitor	true
bspc config pointer_modifier		mod1
bspc config pointer_action1			move
bspc config pointer_action2			resize_side
bspc config click_to_focus			any
bspc config swallow_first_click		false
bspc config ignore_ewmh_focus		true

# ---rules
bspc rule -a Firefox desktop='^4' follow=on focus=on

# ---bar

# ---wallpaper


